version: "3.7"
services:
  api_service:
    build: ../
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysql_db
    networks:
      my-net:
        aliases:
          - my-app
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      my-net:
        aliases:
          - mysql_db

networks:
  my-net: